DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL,
    PASSWD VARCHAR(64) NOT NULL,
    STATUS VARCHAR(128) DEFAULT "",
    CREATED_AT TIMESTAMP DEFAULT now() NOT NULL
)
